; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = 
    ../secrets_config.ini

[env:esp32-c3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	${common.build_flags}
	-DCORE_DEBUG_LEVEL=4
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-std=gnu++2a
	-Wall
	-Wno-comment
	-Wextra
board_upload.before_reset = usb_reset
build_unflags = 
	-std=gnu++11
lib_deps = 
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	robtillaart/AS5600@^0.6.4
